name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: LACOSTAR91
          template: markdown
          filename: README.md
          markdown: https://raw.githubusercontent.com/LACOSTAR91/LACOSTAR91/main/.github/metrics.template.md
          config_output: markdown
          base: header, activity
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_lines: yes
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 1%
          plugin_projects: yes
          plugin_projects_limit: 5
          repositories_skipped: discord-assets
